# Generated by Django 3.2.3 on 2021-06-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='type',
            field=models.ManyToManyField(to='backend.ProductType'),
        ),
    ]
