# Generated by Django 3.2.3 on 2021-05-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_productprice_heat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sweetlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sweetlevel'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='heat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.heatlevel'),
        ),
    ]
