# Generated by Django 3.2.3 on 2021-05-31 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0004_auto_20210529_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaTopping',
            fields=[
                ('orderdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.orderdetail')),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('backend.orderdetail',),
        ),
        migrations.RenameModel(
            old_name='Topping',
            new_name='CoffeeTopping',
        ),
        migrations.RemoveField(
            model_name='sweetlevel',
            name='price',
        ),
    ]
