# Generated by Django 3.2.3 on 2021-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210531_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
